[Variables]
@includeVars=#@#variables.inc
@includeStyles=#@#styles.inc
HeaderSize=#FontSizeH2#

; ------------------------------------------------------------------------------------------------

[Button]
Meter=String

FontColor=#ColorAccent2#
FontSize=#FontSizeText#
FontFace=#FontText#
FontSize=#HeaderSize#
FontFace=#FontHeader#
FontSize=#FontSizeText#
FontFace=#FontText#
AntiAlias=#AntiAlias#

StringStyle=NORMAL
StringCase=UPPER

ClipString=0
SolidColor=0,0,0,1
AntiAlias=1

Text="#Title#"
LeftMouseUpAction=#Command#



