[Variables]
URL=http://www.heise.de/newsticker/heise-atom.xml
Title=Heise
Link=http://www.heise.de/
Entries=25
Expression="(?siU)<title.*>(.*)</title>.*<link.*href="(.*)" />.*<entry.*<title.*>(.*)</title>.*<link.*href="(.*)" />(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)(?(?=.*<entry).*<title.*>(.*)</title>.*<link.*href="(.*)" />)"
