[ValueStringStyle]
FontColor=#ColorAccent2#
FontSize=#FontSizeLabel#
FontFace=#FontValue#
StringEffect=#StringEffect#
StringStyle=BOLD
StringAlign=RIGHT
AntiAlias=#AntiAlias#
NumOfDecimals=2
SolidColor=0,0,0,1
AutoScale=1
H=#FontSizeLabel#

[TextStyle]
ClipString=1
StringStyle=NORMAL
FontColor=#ColorAccent2#
FontSize=#FontSizeText#
FontFace=#FontText#
AntiAlias=#AntiAlias#
SolidColor=0,0,0,1
H=#LineHeight#
W=#MaxTextWidth#
X=2

[SectionHeaderStyle]
FontColor=#ColorHighlight#
FontSize=#FontSizeH2#
FontFace=#FontHeader#
AntiAlias=#AntiAlias#
SolidColor=0,0,0,1
StringCase=UPPER
H=#FontSizeH2#

[SectionHeaderVerticalStyle]
StringAlign=CENTER
FontColor=#ColorHighlight#
FontSize=#FontSizeH2#
FontFace=#FontHeader#
AntiAlias=#AntiAlias#
SolidColor=0,0,0,1
StringCase=UPPER
Angle=1.57
ClipString=1

