[Variables]
@includeScale=#@#_Internal/scale.inc
FontHeader=Century Gothic
FontText=Century Gothic
FontValue=Agency FB
FontSizeH1=(18*#$#)
FontSizeH2=(14*#$#)
FontSizeH3=(10*#$#)
FontSizeText=(10*#$#)
FontSizeLabel=(10*#$#)
StringEffect=None
LineHeight = (20*#$#)
LineSpacing = (0*#$#)
HeaderSpacing = (12*#$#)
MaxTextWidth = (400*#$#)
AntiAlias=1
MaxDL = 52428800
MaxUL = 10485760
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":"","&#39;":"'"

