[Variables]
Title=Tech
Url="https://rss.golem.de/rss.php?feed=ATOM1.0=[golem] https://haptic.al/feed=[haptic] http://virtualrealitysummit.com/feed/=[vrsum] http://feeds.soundcloud.com/users/soundcloud:users:246129251/sounds.rss=[mxcast] https://vrforum.de/forums/vr-technologie.19/index.rss=[vrforum] https://www.gamasutra.com/blogs/rss/=[gsutra] https://www.microsoft.com/de-de/techwiese/feeds/rss/netframework.xml=[dotnet]"
; https://www.sciencedaily.com/rss/computers_math.xml
Prefixes="https://soundcloud.com/user-81308472/vrodocast=[vrodo] https://www.sciencedaily.com/=[science]"
