[Variables]
Title=Tech
Url="https://rss.golem.de/rss.php?feed=ATOM1.0 https://haptic.al/feed http://virtualrealitysummit.com/feed/ https://www.reddit.com/r/virtualreality/.rss http://feeds.soundcloud.com/users/soundcloud:users:246129251/sounds.rss https://vrforum.de/forums/vr-technologie.19/index.rss http://www.gamasutra.com/blogs/rss/ https://www.sciencedaily.com/rss/computers_math.xml"
Prefixes="https://www.golem.de/=[golem] https://www.techstage.de/=[stage] https://haptic.al/=[haptic] http://virtualrealitysummit.com=[vrsum] https://www.reddit.com/r/virtualreality=[reddit/vr] https://www.gamasutra.com/=[gamasutra] https://soundcloud.com/user-81308472/vrodocast=[vrodo] https://vrforum.de/=[vrforum] https://www.sciencedaily.com/=[science]"
